config/routes.rb
Rails.application.routes.draw do
  resources :sightings
  resources :categories
  devise_for :trainers
  resources :trainers, only: [:show]

  root 'sightings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sightings
end

app/models/sighting.rb
class Sighting < ApplicationRecord
  belongs_to :trainer
  belongs_to :category

  acts_as_mappable
  before_validation :geocode_address, :on => :create

  def map_icon
    case category.name
    when "Pokemon"
      "Pokeball.png"
    when "Pokestop"
      "pokemon-moltres.png"
    when "Gym"
      "fight.png"
    end
  end

  private
  def geocode_address
    if lat.blank? || lng.blank?
      geo=Geokit::Geocoders::MultiGeocoder.geocode (full_address)
      errors.add(:full_address, "Could not Geocode address") if !geo.success
      self.lat, self.lng = geo.lat,geo.lng if geo.success
    end
  end
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :sightings

  def name
    "Trainer ##{id}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController

  before_action :authenticate_trainer!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @sightings = Sighting.order(created_at: :desc).limit(7)
    marker_sightings = Sighting.all
    respond_to do |format|
      format.json {
        @markers = sightings_markers(marker_sightings)
        render json: @markers
      }
      format.html {}
    end
  end

  def new
    @sighting = Sighting.new
  end

  def create
    @sighting = current_trainer.sightings.new(sighting_params)

    if @sighting.save
      flash[:success] = "Gotta catch 'em all!"
      redirect_to :root
    else
      flash[:warning] = "Oops. Looks like that sighting escaped the pokeball. Review the errors below and try again."
      render :new
    end
  end

  def edit
    @sighting = current_trainer.sightings.find(params[:id])
  end

  def update
    @sighting = current_trainer.sightings.find(params[:id])

    if @sighting.update(sighting_params)
      flash[:success] = "All updated!"
      redirect_to :root
    else
      flash[:warning] = "Oops. Looks like that sighting escaped the pokeball. Review the errors below and try again."
      render :edit
    end
  end

  def destroy
    @sighting = current_trainer.sightings.find(params[:id])
    @sighting.destroy
    flash[:success] = "A sighting no more. :("
    redirect_to :root
  end

  private

  def sighting_params
    params.require(:sighting).permit(:body, :category_id, :full_address, :lat, :lng)
  end

  def sightings_markers(sightings)
    Gmaps4rails.build_markers(sightings) do |sighting, marker|
      marker.lat sighting.lat
      marker.lng sighting.lng
      marker.infowindow "<img width='50' height='50' src='#{ActionController::Base.helpers.asset_url(sighting.map_icon, type: :image)}' /><p>#{sighting.body}</p>"
    end
  end

end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokeygo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyCkT_Y8SUAc1oD8MCAb9ArBs4lAUBOrqA0"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  </head>

  <body>
     <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "PokeyGo", root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if current_trainer %>
              <li><%= link_to "New Sighting", new_sighting_path %></li>
              <li><%= link_to "Log Out", destroy_trainer_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_trainer_registration_path %></li>
              <li><%= link_to "Log In", new_trainer_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/sightings/_form.html.erb
<%= simple_form_for @sighting do |f| %>
  <%= f.association :category %>
  <%= f.input :body %>
  <%= f.input :full_address %>
  <h6>or ...</h6>
  <%= f.input :lat, label: "Latitude" %>
  <%= f.input :lng, label: "Longitude" %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/sightings/index.html.erb
<div class="col-md-9" id="map_container">
  <div id="map"></div>
</div>
<div class="col-md-3">
  <h4>Recent Sightings</h4>
  <% @sightings.each do |sighting| %>
    <%= simple_format sighting.body %>
    <p class="small"><%= sighting.category.name %> reported by <%= sighting.trainer.name %> on <%= sighting.created_at.to_s(:long) %></p>
  <% end %>
</div>

app/views/sightings/new.html.erb
<h1>Got 'em</h1>

<p>Report your sighting below:</p>

<%= render 'form' %>